### ISSUE TITLE
How can dismiss keyboard?

### ISSUE THREAD

**Issue by ismaiI1** [OmerCora/OCMaskedTextField#3]
dismiss keyboard not working. 

kardeş açık klavyeyi kapatamadım bi türlü. yardımcı olabilir misin? :)

**Comment by OmerCora** [comment]
Textfield'ın kendisi UITextField olmadığı için kendi içine erişmen gerek ([var maskedTextField] seklinde). Örneğin dıştaki view'a dokunulduğunda klavyeyi kapatmak istersen:

``` objective-c
{
    //-viewDidLoad gibi bir yerde
    [self.view addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(asdf)]];
}

-(void)asdf
{
    [[maskedTextField maskedTextField] resignFirstResponder];
}

```

gibi bir mesaj kullanabilirsin.

**Comment by ismaiI1** [comment]
hımm. anladım. teşekkürler. süper bi class. çok beğendim. eline sağlık :+1:

**Comment by OmerCora** [comment]
Rica ederim, issue'yu kapıyorum. İyi çalışmalar! =)
